# Site settings
name: Fly 我是小灰灰
author: yaof
url: https://yaofeifly.github.io
resume_site: https://yaofeifly.github.io/about/
github: https://github.com/yaofeifly/
baseurl: ""
description: fly小灰灰的博客平台!
meta_description: yaof;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 一个炫酷的小码农！
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yaofeifly
highlighter: Rouge

# Build settings
markdown: kramdown

baidu_analysis: da5cbdd8499c1de8f991c49cc0418fe5

